# This file is auto-generated by .github/workflows/update-formula.yml
# Do not edit manually - edit Template/agent-policies.rb instead

class AgentPolicies < Formula
  include Language::Python::Virtualenv

  desc "Policy framework for Claude Code and Cursor AI agents"
  homepage "https://github.com/Devleaps/agent-policies"
  url "https://files.pythonhosted.org/packages/be/fa/361f76afe4a48a3fa1fca8f4588e2970defc7137864f4333ba0e27c32154/devleaps_agent_policies-2.0.0.tar.gz"
  sha256 "a986fe18c5eaed45d2752be7473b541a4df0bcefb37fa3341da9b2e79fa15175"
  license "MIT"

  depends_on "python@3.12"

  def install
    venv = virtualenv_create(libexec, "python3.12")
    venv.pip_install_and_link buildpath
  end

  def caveats
    <<~EOS
      Quick Start:

      Configure hooks:
         devleaps-policy-client install

      Documentation: https://github.com/Devleaps/agent-policies
    EOS
  end

  test do
    assert_match "devleaps-policy-client - Policy enforcement client",
                 shell_output("#{bin}/devleaps-policy-client --help")
  end
end
