# This file is auto-generated by .github/workflows/update-formula.yml
# Do not edit manually - edit Template/agent-policies.rb instead

class AgentPolicies < Formula
  include Language::Python::Virtualenv

  desc "Policy framework for Claude Code and Cursor AI agents"
  homepage "https://github.com/Devleaps/agent-policies"
  url "https://files.pythonhosted.org/packages/ab/4a/1edc0f67a1af808c187cf2d187df5e370b588dd6e303a30d5b42df80eb3c/devleaps_agent_policies-2.1.0.tar.gz"
  sha256 "86b8710f9a203271068ae921e0d5133417a531693fe1ae66c928d3697788b069"
  license "MIT"

  depends_on "python@3.12"

  def install
    venv = virtualenv_create(libexec, "python3.12")
    venv.pip_install_and_link buildpath
  end

  def caveats
    <<~EOS
      Quick Start:

      Configure hooks:
         devleaps-policy-client install

      By default, this uses the Devleaps hosted policy server at:
         https://agent-policies.devleaps.nl

      You can customize the server and other settings in:
         ~/.agent-policies/config.json

      Documentation: https://github.com/Devleaps/agent-policies
    EOS
  end

  test do
    assert_match "devleaps-policy-client - Policy enforcement client",
                 shell_output("#{bin}/devleaps-policy-client --help")
  end
end
